language: python
python:
  - 2.7
  - 3.4
  - 3.5
env:
  - DJANGO_VERSION=1.8.17
  - DJANGO_VERSION=1.9.12
  - DJANGO_VERSION=1.10.4
install:
  - pip install python-coveralls flake8 Django
script:
  - coverage run manage.py test
  - flake8 .
after_success:
  - coveralls
